### ISSUE TITLE
Supporting of generic feature

### ISSUE THREAD

**Issue by MFlisar** [beworker/featured#10]
I would like to be able to define generic features, but the problem is, the generated host does not support it.

Instead of following

```
public class BaseControllerLifecycleFeature extends Feature<BaseControllerLifecycleFeatureHost, Context>
{
    @FeatureEvent
    protected void onConstructor(Controller controller) {}
}
```

I would like to be able to define something like this:

```
public class BaseControllerLifecycleFeature<T extends Controller> extends Feature<BaseControllerLifecycleFeatureHost<T>, Context>
// or public class BaseControllerLifecycleFeature<T extends Controller> extends Feature<BaseControllerLifecycleFeatureHost, Context>
{
    @FeatureEvent
    protected void onConstructor(T controller) {}
}
```

Would it be possible to support this?

**Comment by beworker** [comment]
As for now, annotation processor requires two parameters in the feature class. Thus the following will compile well.

```java
public class BaseControllerLifecycleFeature<T extends Controller, C extends Context> extends Feature<BaseControllerLifecycleFeatureHost, C> {
    @FeatureEvent
    protected void onConstructor(T controller) {}
}
```

**Comment by sergejsha** [comment]
Technically this is possible, but I cannot commit to support it soon due to lack of time.

**Comment by MFlisar** [comment]
I tried that and as soon as I do it, I get following error:

```
Error:(20, 83) error: cannot find symbol class BaseControllerLifecycleFeatureHost
Error:(23, 20) error: unsupported kind: TYPEVAR
```

**Comment by sergejsha** [comment]
You are right, this is not supported. I am not sure when I can find time to support it.

**Comment by MFlisar** [comment]
No problem, I'm deriving from the base class anyways and make this one generic and just cast the controller to T there... Would just be more beautiful the way above.

**Comment by sergejsha** [comment]
Hi @MFlisar. I've just deprecated the project in favor of [Knot](https://github.com/beworker/knot/) library. Featured library can be used further and I might even be able to provide some fixes, if needed. Nevertheless feel free to start writing new features using Knot.

I'm closing this PR as "won't fix" because it's outdated anyway.

**Comment by MFlisar** [comment]
No problem, thanks for the feedback. I already have something for state management as I use MVI in most of my projects and/or redux like stores.
