### ISSUE TITLE
Android X support

### ISSUE THREAD

**Issue by MFlisar** [beworker/featured#12]
Any plans on creating a new branch for android x or for moving on to android x?

Generated code always produces app compat code (e.g. wrong `@NonNull` annotations)

Sadly, the jetifier does not work with generated code and therefore it does not transform it to android x...

If I see it correct, this is the only line in code that would need adjustment: https://github.com/beworker/featured/blob/master/featured-compiler/src/main/java/de/halfbit/featured/compiler/Names.java#L64

**Comment by sergejsha** [comment]
I would rather replace this dependency with `org.jetbrains.annotations` one instead. Will it introduce any issues for you?

**Comment by MFlisar** [comment]
Why not `androidx.annotation.NonNull`? In my android project with android x I can't find `org.jetbrains.annotations`, this would need a special dependecy, wouldn't it?

**Comment by sergejsha** [comment]
This would be a `compile` time dependency which will be added thought `featured` module, fully transparent for you. Projects written in kotlin have this dependency.

> Why not `androidx.annotation.NonNull`?

Because it will introduce versions branching - depending on whether androidx is used of not, users will have to take one or another version of featured library, which is really annoying, also for maintenance. The version with `org.jetbrains.annotations` can be used with or without androidx.

**Comment by MFlisar** [comment]
I did not know this. If so, this of course is a good solution and would help me

**Comment by MFlisar** [comment]
Speaking in old gradle terms using compile/provided:

I need to add the jetbrains dependency via `compile`, so it will be part of the app that uses your library. Because the generated code is generated in the app and therefore you need the dependency in the app as well.

In a library of mine I added an annotation parameter (e.g. `supportLibrary = true`) to avoid dependencies on appcompat and androidx. Maybe this would be a better solution here as well?

I'll make a pull request implementing your suggestion though.

**Comment by MFlisar** [comment]
There's another problem: `android.support.v4.util.ArrayMap`... The android alternative `android.util.ArrayMap` would need min sdk 19....

Any suggestions to solve this?

**Comment by sergejsha** [comment]
>There's another problem: android.support.v4.util.ArrayMap... The android alternative android.util.ArrayMap would need min sdk 19.... Any suggestions to solve this?

I would replace it with a `HashMap` for now.

**Comment by MFlisar** [comment]
I just did this as I saw there's no need for `ArrayMap` anyways, that's why I deleted the comment...

Edit: could solve my own problem
