### ISSUE TITLE
Host with multiple features

### ISSUE THREAD

**Issue by MFlisar** [beworker/featured#6]
I'm sorry for opening so many "issues". This one is an idea only. No problem.

Wouldn't it be nice to be able to create a feature host that can work with many different features? This would make code cleaner I think.

To stick with your example I think that the `SampleFeature` should not include the `onFabClicked` event. This should be defined in a different feature like in a `FabFeature` so that the `SampleFesture` becomes a `LifecycleFeature`. Still it makes sense to be able to create a host that combines those two features.

What do you think about that?

**Comment by sergejsha** [comment]
You are right. I also identified this need. 

But keep in mind, that featured is not an event bus. The main difference is that features define a lifecycle contract they expect to be fulfilled by feature host (or rather the class dispatching those events via feature host). In contrast, classes registered at an event bus make no implication about oder or presents of events.

Currently, features can be inherited. It means you can already build feature inheritance you described. Each feature inheritance level will have its own feature hosts, which are also inherited. What is not implemented is the capability of reuse more generic features in inherited feature hosts. This is what I am working on in `feature-lifecycle-inheritance` branch. It should come soon. 

Combination of features is an interesting idea too. I need to think about it.
